<?php
/**
 * Created by PhpStorm.
 * User: ztl8702
 * Date: 9/06/16
 * Time: 4:47 PM
 */

namespace Drupal\wcr\Plugin\Derivative;


use Drupal\Component\Plugin\Derivative\DeriverBase;

class DynamicBlockExportLinks extends DeriverBase{


  public function getDerivativeDefinitions($base_plugin_definition) {
    return parent::getDerivativeDefinitions($base_plugin_definition); // TODO: Change the autogenerated stub
  }
}