<?php
/**
 * @file
 * Contains \Drupal\block_export_ui\Plugin\Derivative\DynamicBlockExportLinks.
 */

namespace Drupal\block_export_ui\Plugin\Derivative;


use Drupal\Component\Plugin\Derivative\DeriverBase;

class DynamicBlockExportLinks extends DeriverBase{

  /**
   * @param array $base_plugin_definition
   * @return array
   */
  public function getDerivativeDefinitions($base_plugin_definition) {
    return parent::getDerivativeDefinitions($base_plugin_definition);
    // TODO: Change the autogenerated stub
  }
}
